In [2]:
import os
import pdb
import sys
import glob
import numpy as np
import pandas as pd

sys.path.append('/Users/annayang/Documents/QueenBee/Bee_NotBee_classification')
from info import i, printb, printr, printp

from utils import load_audioFiles_saves_segments, write_Statelabels_from_samplesFolder, get_uniqueHives_names_from_File, get_samples_id_perSet, get_features_from_samples, get_GT_labels_fromFiles, labels2binary, get_list_samples_names, split_samples_ramdom

In [108]:
path_audioFiles="/Users/annayang/Documents/QueenBee/MyDataset"+os.sep  # path to audio files
path_save_audio_labels='/Users/annayang/Documents/QueenBee/SingleHiveDataset'+os.sep  # path where to save audio segments and labels files.
path_raw_state_labels = '/Users/annayang/Documents/QueenBee/raw_state_labels.csv'

In [23]:
full = pd.read_csv(path_raw_state_labels).set_index('Unnamed: 0').reset_index(drop=True)

In [85]:
full['device'] = full['file name'].str[-1:]
full.iloc[27]

file name         2022-06-09--03-13-35_1
queen presence                         0
device                                 1
Name: 27, dtype: object

In [89]:
singleHive = full[full['device'] == '2']
singleHive.reset_index(drop=True)

                  file name  queen presence device
0    2022-06-09--03-13-33_2               0      2
1    2022-06-08--18-21-07_2               0      2
2    2022-06-08--19-20-13_2               0      2
3    2022-06-08--20-19-23_2               0      2
4    2022-06-08--21-18-28_2               0      2
..                      ...             ...    ...
104  2022-06-11--08-33-45_2               1      2
105  2022-06-11--09-34-20_2               1      2
106  2022-06-11--10-33-55_2               1      2
107  2022-06-11--11-33-12_2               1      2
108  2022-06-08--03-54-28_2               1      2

[109 rows x 3 columns]

## take data from 6/5/2022	5:40:45 PM to 6/9/2022	6:40:00 PM

In [102]:
sort = singleHive.sort_values(by=['file name']).reset_index(drop=True)
sort

                  file name  queen presence device
0    2022-06-08--03-54-28_2               1      2
1    2022-06-08--04-53-41_2               1      2
2    2022-06-08--05-52-54_2               1      2
3    2022-06-08--06-52-11_2               1      2
4    2022-06-08--07-51-48_2               1      2
..                      ...             ...    ...
104  2022-06-13--10-49-36_2               1      2
105  2022-06-13--11-48-58_2               1      2
106  2022-06-13--12-48-18_2               1      2
107  2022-06-13--13-47-23_2               1      2
108  2022-06-13--14-46-29_2               1      2

[109 rows x 3 columns]

In [103]:
sort = sort[0:34]
sort

                 file name  queen presence device
0   2022-06-08--03-54-28_2               1      2
1   2022-06-08--04-53-41_2               1      2
2   2022-06-08--05-52-54_2               1      2
3   2022-06-08--06-52-11_2               1      2
4   2022-06-08--07-51-48_2               1      2
5   2022-06-08--08-51-21_2               1      2
6   2022-06-08--09-50-41_2               1      2
7   2022-06-08--14-52-43_2               0      2
8   2022-06-08--15-51-41_2               0      2
9   2022-06-08--17-22-00_2               0      2
10  2022-06-08--18-21-07_2               0      2
11  2022-06-08--19-20-13_2               0      2
12  2022-06-08--20-19-23_2               0      2
13  2022-06-08--21-18-28_2               0      2
14  2022-06-08--22-17-37_2               0      2
15  2022-06-08--23-16-48_2               0      2
16  2022-06-09--00-15-57_2               0      2
17  2022-06-09--01-15-07_2               0      2
18  2022-06-09--02-14-21_2               0      2
19  2022-06-09--03-13-33_2               0      2
20  2022-06-09--04-12-46_2               0      2
21  2022-06-09--05-11-59_2               0      2
22  2022-06-09--06-11-10_2               0      2
23  2022-06-09--07-10-29_2               0      2
24  2022-06-09--08-09-48_2               0      2
25  2022-06-09--09-09-12_2               0      2
26  2022-06-09--10-08-31_2               0      2
27  2022-06-09--11-07-46_2               0      2
28  2022-06-09--12-07-14_2               0      2
29  2022-06-09--13-06-37_2               0      2
30  2022-06-09--14-05-39_2               0      2
31  2022-06-09--15-04-51_2               0      2
32  2022-06-09--16-04-05_2               0      2
33  2022-06-09--17-03-21_2               0      2

In [105]:
sort = sort.drop('device', axis = 1)
sort

                 file name  queen presence
0   2022-06-08--03-54-28_2               1
1   2022-06-08--04-53-41_2               1
2   2022-06-08--05-52-54_2               1
3   2022-06-08--06-52-11_2               1
4   2022-06-08--07-51-48_2               1
5   2022-06-08--08-51-21_2               1
6   2022-06-08--09-50-41_2               1
7   2022-06-08--14-52-43_2               0
8   2022-06-08--15-51-41_2               0
9   2022-06-08--17-22-00_2               0
10  2022-06-08--18-21-07_2               0
11  2022-06-08--19-20-13_2               0
12  2022-06-08--20-19-23_2               0
13  2022-06-08--21-18-28_2               0
14  2022-06-08--22-17-37_2               0
15  2022-06-08--23-16-48_2               0
16  2022-06-09--00-15-57_2               0
17  2022-06-09--01-15-07_2               0
18  2022-06-09--02-14-21_2               0
19  2022-06-09--03-13-33_2               0
20  2022-06-09--04-12-46_2               0
21  2022-06-09--05-11-59_2               0
22  2022-06-09--06-11-10_2               0
23  2022-06-09--07-10-29_2               0
24  2022-06-09--08-09-48_2               0
25  2022-06-09--09-09-12_2               0
26  2022-06-09--10-08-31_2               0
27  2022-06-09--11-07-46_2               0
28  2022-06-09--12-07-14_2               0
29  2022-06-09--13-06-37_2               0
30  2022-06-09--14-05-39_2               0
31  2022-06-09--15-04-51_2               0
32  2022-06-09--16-04-05_2               0
33  2022-06-09--17-03-21_2               0

In [106]:
sort.to_csv(path_save_audio_labels+'raw_state_labels.csv')

In [154]:
sort_balanced = sort[0:15]
sort_balanced

                 file name  queen presence
0   2022-06-08--03-54-28_2               1
1   2022-06-08--04-53-41_2               1
2   2022-06-08--05-52-54_2               1
3   2022-06-08--06-52-11_2               1
4   2022-06-08--07-51-48_2               1
5   2022-06-08--08-51-21_2               1
6   2022-06-08--09-50-41_2               1
7   2022-06-08--14-52-43_2               0
8   2022-06-08--15-51-41_2               0
9   2022-06-08--17-22-00_2               0
10  2022-06-08--18-21-07_2               0
11  2022-06-08--19-20-13_2               0
12  2022-06-08--20-19-23_2               0
13  2022-06-08--21-18-28_2               0
14  2022-06-08--22-17-37_2               0

## data processing now... (with their code)

In [109]:
full_audiofilenames_list = [os.path.basename(x) for x in glob.glob(path_audioFiles+'*.wav')]

In [155]:
audiofilenames_list = []
for filename in [os.path.basename(x) for x in glob.glob(path_audioFiles+'*.wav')]:
    # print(filename[:-14])
    if filename[:-14] in list(sort_balanced['file name']):
        audiofilenames_list.append(filename)

In [156]:
from scipy.io import wavfile

for filename in audiofilenames_list:
    samplerate, data = wavfile.read(path_audioFiles+filename)
    wavfile.write(path_save_audio_labels+filename, samplerate, data)

In [157]:
write_Statelabels_from_samplesFolder(path_save_audio_labels, path_save_audio_labels, sort)

2022-06-08--09-50-41_2
2022-06-08--09-50-41_2
2022-06-08--09-50-41_2
2022-06-08--20-19-23_2
2022-06-08--20-19-23_2
2022-06-08--09-50-41_2
2022-06-08--05-52-54_2
2022-06-08--20-19-23_2
2022-06-08--20-19-23_2
2022-06-08--05-52-54_2
2022-06-08--05-52-54_2
2022-06-08--09-50-41_2
2022-06-08--20-19-23_2
2022-06-08--20-19-23_2
2022-06-08--09-50-41_2
2022-06-08--06-52-11_2
2022-06-08--18-21-07_2
2022-06-08--03-54-28_2
2022-06-08--03-54-28_2
2022-06-08--06-52-11_2
2022-06-08--18-21-07_2
2022-06-08--18-21-07_2
2022-06-08--06-52-11_2
2022-06-08--18-21-07_2
2022-06-08--06-52-11_2
2022-06-08--06-52-11_2
2022-06-08--18-21-07_2
2022-06-08--03-54-28_2
2022-06-08--03-54-28_2
2022-06-08--06-52-11_2
2022-06-08--18-21-07_2
2022-06-08--03-54-28_2
2022-06-08--03-54-28_2
2022-06-08--14-52-43_2
2022-06-08--14-52-43_2
2022-06-08--17-22-00_2
2022-06-08--17-22-00_2
2022-06-08--17-22-00_2
2022-06-08--14-52-43_2
2022-06-08--14-52-43_2
2022-06-08--17-22-00_2
2022-06-08--17-22-00_2
2022-06-08--14-52-43_2
2022-06-08--14-52-43_2
2022-06-08--17-22-00_2
2022-06-08--15-51-41_2
2022-06-08--19-20-13_2
2022-06-08--08-51-21_2
2022-06-08--07-51-48_2
2022-06-08--21-18-28_2
2022-06-08--21-18-28_2
2022-06-08--07-51-48_2
2022-06-08--08-51-21_2
2022-06-08--19-20-13_2
2022-06-08--15-51-41_2
2022-06-08--22-17-37_2
2022-06-08--15-51-41_2
2022-06-08--07-51-48_2
2022-06-08--08-51-21_2
2022-06-08--04-53-41_2
2022-06-08--21-18-28_2
2022-06-08--21-18-28_2
2022-06-08--04-53-41_2
2022-06-08--08-51-21_2
2022-06-08--07-51-48_2
2022-06-08--15-51-41_2
2022-06-08--22-17-37_2
2022-06-08--22-17-37_2
2022-06-08--15-51-41_2
2022-06-08--19-20-13_2
2022-06-08--08-51-21_2
2022-06-08--21-18-28_2
2022-06-08--04-53-41_2
2022-06-08--04-53-41_2
2022-06-08--21-18-28_2
2022-06-08--08-51-21_2
2022-06-08--19-20-13_2
2022-06-08--15-51-41_2
2022-06-08--22-17-37_2
2022-06-08--22-17-37_2
2022-06-08--19-20-13_2
2022-06-08--07-51-48_2
2022-06-08--04-53-41_2
2022-06-08--04-53-41_2
2022-06-08--07-51-48_2
2022-06-08--19-20-13_2
2022-06-08--22-17-37_2

In [159]:
from collections import Counter
Counter(sort_balanced['queen presence'])

Counter({1: 7, 0: 8})

In [160]:
state_labels = pd.read_csv('/Users/annayang/Documents/QueenBee/singleHiveDataset/state_labels.csv')

In [161]:
for i in range(3):
    split_dict = split_samples_ramdom(0.1,0.2,path_save_audio_labels, path_save_audio_labels+'split_random_'+str(i))

In [162]:
import json
split = json.load(open('/Users/annayang/Documents/QueenBee/singleHiveDataset/split_random_0.json'))

In [163]:
len(split['test'])

9

In [164]:
len(split['train'])

62

In [165]:
len(split['val'])

16

In [166]:
Counter(state_labels['label'])

Counter({'active': 39, 'missing queen': 48})